apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-anagrams-job
spec:
  template:
    spec:
      container:
        -
          image: maxreig/ibm-anagrams:latest
          name: ibm-anagrams-container
          volumeMounts:
            -
              mountPath: /data
              name: ibm-anagrams-volume
              readOnly: true
      initContainers:
        -
          command:
            - sh
            - '-c'
            - 'set -x; cd/downloads; rm -f ${FILENAME}; wget ${URL}/${FILENAME}'
          env:
            -
              name: FILENAME
              valeuFrom:
                secretKeyRef:
                  key: filename
                  name: ibm-anagram-secret
            -
              name: URL
              valeuFrom:
                secretKeyRef:
                  key: url
                  name: ibm-anagram-secret
          image: busybox
          name: ibm-anagrams-initContainer
          volumeMounts:
            -
              mountPath: /downloads
              name: ibm-anagrams-volume
              readOnly: false
      restartPolicy: OnFailure
      volumnes:
        -
          #emptyDir: {}
          name: ibm-anagrams-volume
          persistentVolumeClaim:
            claimName: ibm-anagrams-pvc
            readOnly: false
            
          
          
              
        
            
            
        
  
